import { prisma } from "@/lib/prisma";
import { findPrimaryAccount, createIncomeFromPayment } from "@/repositories/finance";

/**
 * Create a payment record for an event.
 * If paidBy is "VENDOR", auto-verify (vendor-recorded payments are trusted).
 */
export async function createPayment(data: {
  eventId: string;
  paymentType: "DOWN_PAYMENT" | "FULL_PAYMENT" | "INSTALLMENT";
  amount: number;
  currency?: string;
  note?: string | null;
  receiptUrl?: string | null;
  receiptName?: string | null;
  paidBy?: "VENDOR" | "CLIENT";
}) {
  const isVendor = data.paidBy === "VENDOR";
  const payment = await prisma.payment.create({
    data: {
      eventId: data.eventId,
      paymentType: data.paymentType,
      amount: data.amount,
      currency: data.currency ?? "IDR",
      note: data.note ?? undefined,
      receiptUrl: data.receiptUrl ?? undefined,
      receiptName: data.receiptName ?? undefined,
      paidBy: data.paidBy ?? "CLIENT",
      isVerified: isVendor, // auto-verify vendor-recorded payments
    },
  });

  // If this is a vendor-recorded payment, attempt to auto-create an
  // INCOME finance transaction in the vendor's primary account.
  if (isVendor) {
    try {
      const event = await prisma.event.findUnique({
        where: { id: data.eventId },
        select: { businessProfileId: true, clientName: true, eventType: true },
      });

      if (event?.businessProfileId) {
        const primary = await findPrimaryAccount(event.businessProfileId);
        if (primary) {
          // Guard against duplicate transactions for the same payment by
          // checking for an existing transaction that references the
          // payment id suffix used in the autogenerated notes.
          const suffix = payment.id.slice(-8);
          const exists = await prisma.financeTransaction.findFirst({
            where: {
              eventId: data.eventId,
              notes: { contains: suffix },
            },
          });
          if (!exists) {
            await createIncomeFromPayment({
              businessProfileId: event.businessProfileId,
              primaryAccountId: primary.id,
              paymentId: payment.id,
              amount: Number(payment.amount),
              currency: payment.currency ?? undefined,
              eventId: data.eventId,
              clientName: event.clientName,
              eventType: event.eventType,
              paymentType: payment.paymentType,
              receiptUrl: payment.receiptUrl ?? null,
              receiptName: payment.receiptName ?? null,
            });
          }
        }
      }
    } catch (err) {
      // Non-fatal: payment creation should succeed even if finance recording fails.
      console.error("[payments] auto-create finance transaction failed:", err);
    }
  }

  return payment;
}

// NOTE: We intentionally keep finance-side recording here in the repository so
// any caller that creates/verifies a payment will also attempt to auto-create
// an INCOME transaction for bookkeeping. We guard against duplicates by
// searching for an existing transaction whose notes contain the payment suffix.

/**
 * Verify a payment receipt (vendor confirms).
 */
export async function verifyPayment(id: string) {
  const updated = await prisma.payment.update({
    where: { id },
    data: { isVerified: true },
  });

  // When a payment becomes verified, create an INCOME transaction if possible.
  if (updated.isVerified) {
    try {
      const event = await prisma.event.findUnique({
        where: { id: updated.eventId },
        select: { businessProfileId: true, clientName: true, eventType: true },
      });

      if (event?.businessProfileId) {
        const primary = await findPrimaryAccount(event.businessProfileId);
        if (primary) {
          const suffix = updated.id.slice(-8);
          const exists = await prisma.financeTransaction.findFirst({
            where: { eventId: updated.eventId, notes: { contains: suffix } },
          });
          if (!exists) {
            await createIncomeFromPayment({
              businessProfileId: event.businessProfileId,
              primaryAccountId: primary.id,
              paymentId: updated.id,
              amount: Number(updated.amount),
              currency: updated.currency ?? undefined,
              eventId: updated.eventId,
              clientName: event.clientName,
              eventType: event.eventType,
              paymentType: updated.paymentType,
              receiptUrl: updated.receiptUrl ?? null,
              receiptName: updated.receiptName ?? null,
            });
          }
        }
      }
    } catch (err) {
      console.error("[payments] auto-create finance transaction on verify failed:", err);
    }
  }

  return updated;
}

/**
 * Reject / unverify a payment (vendor disagrees).
 */
export async function rejectPayment(id: string) {
  return prisma.payment.update({
    where: { id },
    data: { isVerified: false },
  });
}

/**
 * Find a single payment by ID.
 */
export async function findPaymentById(id: string) {
  return prisma.payment.findUnique({ where: { id } });
}

/**
 * Find all payments for an event.
 */
export async function findPaymentsByEvent(eventId: string) {
  return prisma.payment.findMany({
    where: { eventId },
    orderBy: { paidAt: "desc" },
  });
}

/**
 * Recalculate and update event payment status based on verified payments total.
 */
export async function recalcPaymentStatus(eventId: string) {
  const allPayments = await prisma.payment.findMany({
    where: { eventId },
  });
  const event = await prisma.event.findUnique({
    where: { id: eventId },
    select: { amount: true },
  });

  const totalPaid = allPayments
    .filter((p) => p.isVerified)
    .reduce((sum, p) => sum + Number(p.amount), 0);
  const totalAmount = Number(event?.amount ?? 0);

  let newStatus: "UNPAID" | "DP_PAID" | "PAID" = "UNPAID";
  if (totalPaid > 0 && totalPaid < totalAmount) {
    newStatus = "DP_PAID";
  } else if (totalPaid >= totalAmount && totalAmount > 0) {
    newStatus = "PAID";
  }

  // Build the update payload: always update paymentStatus,
  // and auto-promote eventStatus to BOOKED when first payment arrives.
  const updateData: Record<string, unknown> = { paymentStatus: newStatus };

  if (newStatus !== "UNPAID") {
    const currentEvent = await prisma.event.findUnique({
      where: { id: eventId },
      select: { eventStatus: true },
    });
    if (
      currentEvent?.eventStatus === "INQUIRY" ||
      currentEvent?.eventStatus === "WAITING_CONFIRMATION"
    ) {
      updateData.eventStatus = "BOOKED";
    }
  }

  await prisma.event.update({
    where: { id: eventId },
    data: updateData,
  });

  return newStatus;
}
